/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.AdicionarTipoMaterialController;
import java.awt.EventQueue;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Simulacao;
import static model.Simulacao.getIdiomaAtual;

/**
 *
 * @author DC_G2
 */
public class AdicionarTipoMaterialUI extends javax.swing.JDialog {

    /**
     * A simulação a usar.
     */
    private Simulacao sim;

    /**
     * O controller que irá coordenar este caso de uso.
     */
    private AdicionarTipoMaterialController controller;
    
    private java.awt.Frame framePai;
    

    /**
     * Creates new form AdicionarTipoMaterialUI
     */
    public AdicionarTipoMaterialUI(java.awt.Frame parent, boolean modal, Simulacao sim) {
        super(parent, modal);
        initComponents();
        this.sim = sim;
        this.controller = new AdicionarTipoMaterialController(sim);
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                DefaultListModel<String> model = new DefaultListModel();
                List<String> materiais = controller.getListaMateriaisString();
                for (String element : materiais) {
                    model.addElement(element);
                }
                listaMateriais.setModel(model);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaMateriais = new javax.swing.JList<String>();
        lblListaMateriais = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        lblCoefConducao = new javax.swing.JLabel();
        lblCoefConvec = new javax.swing.JLabel();
        lblCoefRadiacao = new javax.swing.JLabel();
        btnAdicionarMaterial = new javax.swing.JButton();
        btnAdicionarImagem = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        txtCoefCond = new javax.swing.JTextField();
        txtCoefConv = new javax.swing.JTextField();
        txtCoefRad = new javax.swing.JTextField();
        txtCaminho = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();

        setResizable(false);

        jScrollPane1.setViewportView(listaMateriais);

        lblListaMateriais.setText(Simulacao.getFrasePelaChave("uc3.label.listaMaterial")
        );

        lblNome.setText(Simulacao.getFrasePelaChave("uc3.label.materialNome"));

        lblDescricao.setText(Simulacao.getFrasePelaChave("uc3.label.materialDescricao"));

        lblCoefConducao.setText(Simulacao.getFrasePelaChave("uc3.label.materialCoefCond"));

        lblCoefConvec.setText(Simulacao.getFrasePelaChave("uc3.label.materialCoefConv"));

        lblCoefRadiacao.setText(    Simulacao.getFrasePelaChave("uc3.label.materialCoefRad"));

        btnAdicionarMaterial.setText(Simulacao.getFrasePelaChave("uc3.btn.adicionarMaterial"));
        btnAdicionarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMaterialActionPerformed(evt);
            }
        });

        btnAdicionarImagem.setText(Simulacao.getFrasePelaChave("uc3.btn.selecionarImagem"));
        btnAdicionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarImagemActionPerformed(evt);
            }
        });

        txtCaminho.setEditable(false);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane2.setViewportView(txtDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblListaMateriais)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdicionarMaterial)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCoefConducao)
                                            .addComponent(lblCoefConvec)
                                            .addComponent(lblCoefRadiacao))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCoefConv, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtNome)
                                            .addComponent(txtCoefRad)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCoefCond, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(btnAdicionarImagem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCaminho)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblListaMateriais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescricao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCoefCond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCoefConducao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoefConvec)
                    .addComponent(txtCoefConv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoefRadiacao)
                    .addComponent(txtCoefRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarImagem)
                    .addComponent(txtCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnAdicionarMaterial)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarImagemActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setFileFilter(new FileNameExtensionFilter("Joint Photographics Group (JPG)","jpg","jpeg"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Portable Network Graphics (PNG)","png"));
        int result = chooser.showOpenDialog(this);
        switch (result)
        {
            case JFileChooser.APPROVE_OPTION:
                txtCaminho.setText(chooser.getSelectedFile().getAbsolutePath());
            break;
        }
    }//GEN-LAST:event_btnAdicionarImagemActionPerformed

    private void btnAdicionarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMaterialActionPerformed
        try {
            this.controller.novoMaterial(txtNome.getText(), txtDescricao.getText(),
                    Double.parseDouble(txtCoefCond.getText()),
                    Double.parseDouble(txtCoefConv.getText()),
                    Double.parseDouble(txtCoefRad.getText()), ImageIO.read(new File(txtCaminho.getText())));

            String opcoes[] = {Simulacao.getFrasePelaChave("menu.sim"), Simulacao.getFrasePelaChave("menu.nao")};
            int resposta = JOptionPane.showOptionDialog(
                    null, Simulacao.getFrasePelaChave("uc3.janela.mensagem"),
                    Simulacao.getFrasePelaChave("uc3.janela.titulo"), 0,
                    JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
            if (resposta == JOptionPane.OK_OPTION) {
                if (this.controller.RegistaMaterial())
                {
                    JOptionPane.showMessageDialog(this,Simulacao.getFrasePelaChave("uc3.register.successful"),"",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(this,Simulacao.getFrasePelaChave("uc3.register.error"),"",JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    Simulacao.getFrasePelaChave("uc3.janela.titulo"),
                    JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(AdicionarTipoMaterialUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdicionarMaterialActionPerformed

    private void adicionarJanelaMaterial() {
        lblListaMateriais.setText(getIdiomaAtual().getString("uc3.label.listaMaterial"));
        lblNome.setText(getIdiomaAtual().getString("uc3.label.materialNome"));
        lblDescricao.setText(getIdiomaAtual().getString("uc3.label.materialDescricao"));
        lblCoefConducao.setText(getIdiomaAtual().getString("uc3.label.materialCoefCond"));
        lblCoefConvec.setText(getIdiomaAtual().getString("uc3.label.materialCoefConv"));
        lblCoefRadiacao.setText(getIdiomaAtual().getString("uc3.label.materialCoefRad"));
        btnAdicionarImagem.setText(getIdiomaAtual().getString("uc3.btn.selecionarImagem"));
        btnAdicionarMaterial.setText(getIdiomaAtual().getString("uc3.btn.adicionarMaterial"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarImagem;
    private javax.swing.JButton btnAdicionarMaterial;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCoefConducao;
    private javax.swing.JLabel lblCoefConvec;
    private javax.swing.JLabel lblCoefRadiacao;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblListaMateriais;
    private javax.swing.JLabel lblNome;
    private javax.swing.JList<String> listaMateriais;
    private javax.swing.JTextField txtCaminho;
    private javax.swing.JTextField txtCoefCond;
    private javax.swing.JTextField txtCoefConv;
    private javax.swing.JTextField txtCoefRad;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
