/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bragasQuest.PointDouble;
import controllers.AlterarTemperaturasMeioController;
import java.awt.EventQueue;
import javax.swing.JOptionPane;
import model.Simulacao;

/**
 *
 * @author Diogo
 */
public class AlterarTemperaturasUI extends javax.swing.JDialog {

    
    private AlterarTemperaturasMeioController controller;
    /**
     * Creates new form AlterarTemperaturasUI
     */
    public AlterarTemperaturasUI(java.awt.Frame parent, boolean modal,Simulacao sim) {
        super(parent, modal);
        initComponents();
        controller = new AlterarTemperaturasMeioController(sim);
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                tempIntField.setText(String.valueOf(controller.getTemperaturaInterior()));
                tempIntAlvoField.setText(String.valueOf(controller.getTemperaturaInteriorAlvo()));
                tempExtField.setText(String.valueOf(controller.getTemperaturaExterior()));
                tempExtMinField.setText(String.valueOf(controller.getTemperaturaExteriorMinima()));
                tempExtMaxField.setText(String.valueOf(controller.getTemperaturaExteriorMaxima()));
                radioButton.setSelected(controller.hasTemperaturaVariation());
                updateFieldsOnRadio();
                plotGraph.setDivisionFactor(16);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        plotGraph = new bragasQuest.PlotGraph();
        jLabel1 = new javax.swing.JLabel();
        tempIntField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioButton = new javax.swing.JRadioButton();
        tempIntAlvoField = new javax.swing.JTextField();
        tempExtField = new javax.swing.JTextField();
        tempExtMinField = new javax.swing.JTextField();
        tempExtMaxField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout plotGraphLayout = new javax.swing.GroupLayout(plotGraph);
        plotGraph.setLayout(plotGraphLayout);
        plotGraphLayout.setHorizontalGroup(
            plotGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        plotGraphLayout.setVerticalGroup(
            plotGraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText(Simulacao.getFrasePelaChave("uc2.tempInt"));

        jLabel2.setText(Simulacao.getFrasePelaChave("uc2.graph")
        );

        jLabel3.setText(Simulacao.getFrasePelaChave("uc2.tempIntAlvo"));

        jLabel4.setText(Simulacao.getFrasePelaChave("uc2.tempExt"));

        jLabel5.setText(Simulacao.getFrasePelaChave("uc2.tempExtMin"));

        jLabel6.setText(Simulacao.getFrasePelaChave("uc2.tempExtMax"));

        radioButton.setText(Simulacao.getFrasePelaChave("uc2.hasVariation"));
        radioButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                radioButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("ºC");

        jLabel8.setText("ºC");

        jLabel9.setText("ºC");

        jLabel10.setText("ºC");

        jLabel11.setText("ºC");

        acceptButton.setText(Simulacao.getFrasePelaChave("uc2.button.accept")
        );
        acceptButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                acceptButtonActionPerformed(evt);
            }
        });

        exitButton.setText(Simulacao.getFrasePelaChave("uc2.button.exit")
        );
        exitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButtonActionPerformed(evt);
            }
        });

        updateButton.setText(Simulacao.getFrasePelaChave("uc2.button.update"));
        updateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plotGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempIntAlvoField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempExtField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempExtMinField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempExtMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(radioButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempIntField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(acceptButton)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tempIntField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tempIntAlvoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tempExtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tempExtMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tempExtMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(updateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plotGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptButton)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            double tempInt = Double.parseDouble(tempIntField.getText());
            double tempIntAlvo = Double.parseDouble(tempIntAlvoField.getText());
            double tempExt = Double.parseDouble(tempIntField.getText());
            boolean hasVariation = radioButton.isSelected();
            if (hasVariation)
            {
                double tempExtMin = Double.parseDouble(tempExtMinField.getText());
                double tempExtMax = Double.parseDouble(tempExtMaxField.getText());
                controller.setTemperaturaExteriorMinima(tempExtMin);
                controller.setTemperaturaExteriorMaxima(tempExtMax);
            }
            controller.setTemperaturaInterior(tempInt);
            controller.setTemperaturaInteriorAlvo(tempIntAlvo);
            controller.setTemperaturaExterior(tempExt);
            controller.setHasTemperaturaVariation(hasVariation);
            if (controller.valida())
            {
                controller.alterarSala();
                JOptionPane.showMessageDialog(this,Simulacao.getFrasePelaChave("uc2.operation.success"),"",JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this,Simulacao.getFrasePelaChave("uc2.operation.failure"),"",JOptionPane.ERROR_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this,Simulacao.getFrasePelaChave("uc2.number.exception"),"",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActionPerformed
        // TODO add your handling code here:
        updateFieldsOnRadio();
    }//GEN-LAST:event_radioButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            plotGraph.clearPoints();
            double min=Double.parseDouble(tempExtMinField.getText()),max=Double.parseDouble(tempExtMaxField.getText());
            int pointNumber=30;
            plotGraph.setXScale(12);
            plotGraph.setYScale(1);
            double maxVal = 2d*Math.PI;
            double iteration = maxVal/((double)pointNumber);
            double y;
            for (double i=0;i<maxVal;i+=iteration)
            {
                y=(min+max)*0.5+(0.5*(max-min)*Math.sin(i));
                plotGraph.addPoint(new PointDouble(i,y));
            }
            repaint();
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this,Simulacao.getFrasePelaChave("uc2.number.exception"),"",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_exitButtonActionPerformed
    {//GEN-HEADEREND:event_exitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void updateFieldsOnRadio()
    {
        tempExtMinField.setEnabled(radioButton.isSelected());
        tempExtMaxField.setEnabled(radioButton.isSelected());
        updateButton.setEnabled(radioButton.isSelected());
        plotGraph.setEnabled(radioButton.isSelected());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private bragasQuest.PlotGraph plotGraph;
    private javax.swing.JRadioButton radioButton;
    private javax.swing.JTextField tempExtField;
    private javax.swing.JTextField tempExtMaxField;
    private javax.swing.JTextField tempExtMinField;
    private javax.swing.JTextField tempIntAlvoField;
    private javax.swing.JTextField tempIntField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
