package view;

import controllers.AlterarPropriedadesSalaController;
import java.awt.EventQueue;
import java.awt.Frame;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Simulacao;

/**
 *
 */
public class AlterarParedeUI extends javax.swing.JDialog {

    private Frame framePai;
    private Simulacao simulacao;
    private AlterarPropriedadesSalaController controller;
    private int indexParede;
    private DefaultListModel<String> modelMat;
    private DefaultListModel<String> modelEsp;
    
    /**
     * Creates new form AlterarParedeUI
     * 
     * @param parent
     * @param modal
     * @param controller
     * @param simulacao
     * @param index
     */
    public AlterarParedeUI(java.awt.Frame parent, boolean modal, final
            AlterarPropriedadesSalaController controller, Simulacao simulacao, int index) {
        super(parent, modal);
        framePai = parent;
        this.simulacao = simulacao;
        this.controller = controller;
        controller.backupParede(index);
        controller.novoListaParedes(index);
        indexParede = index;
        initComponents();
        EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                modelMat = new DefaultListModel();
                modelEsp = new DefaultListModel();
                listMateriais.setModel(modelMat);
                listEspessuras.setModel(modelEsp);
                tempField.setText(String.format("%.2f",controller.getTemperatura(indexParede)).replace(",","."));
                updateList();
            }
        });
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        spMateriais = new javax.swing.JScrollPane();
        listMateriais = new javax.swing.JList<String>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        spEspessuras = new javax.swing.JScrollPane();
        listEspessuras = new javax.swing.JList<String>();
        btnRemover = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tempField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        spMateriais.setViewportView(listMateriais);

        btnCancelar.setText(Simulacao.getFrasePelaChave("uc1.janela.cancelar"));
        btnCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setText(Simulacao.getFrasePelaChave("uc1.janela.guardar"));
        btnGuardar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGuardarActionPerformed(evt);
            }
        });

        listEspessuras.setEnabled(false);
        spEspessuras.setViewportView(listEspessuras);

        btnRemover.setText(Simulacao.getFrasePelaChave("uc1.janela.remover"));
        btnRemover.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemoverActionPerformed(evt);
            }
        });

        btnAdicionar.setText(Simulacao.getFrasePelaChave("uc1.janela.adicionar"));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel1.setText(Simulacao.getFrasePelaChave("uc1.janela.temperatura"));

        jLabel2.setText(Simulacao.getFrasePelaChave("uc1.janela.espessura"));

        jLabel3.setText(Simulacao.getFrasePelaChave("uc1.janela.material"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spEspessuras, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMateriais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spEspessuras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemover)
                    .addComponent(btnAdicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {spEspessuras, spMateriais});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdicionar, btnRemover});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        controller.revertParedeChanges(indexParede);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        new AdicionarMaterialParedeUI(framePai, true, controller, simulacao, indexParede,this);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        try {
            int i = listMateriais.getSelectedIndex();
            controller.removerMaterial(indexParede, i);
            updateList();
            framePai.revalidate();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    Simulacao.getFrasePelaChave("uc1.janela.titulo"),
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String opcoes[] = {Simulacao.getFrasePelaChave("menu.sim"), Simulacao.getFrasePelaChave("menu.nao")};
            int resposta = JOptionPane.showOptionDialog(
                    null, Simulacao.getFrasePelaChave("uc1.janela.mensagem"),
                    Simulacao.getFrasePelaChave("uc1.janela.titulo"), 0,
                    JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
            if (resposta == 0 ) {
                double temperatura
                        = Double.parseDouble(this.tempField.getText());
                controller.guardarParede(indexParede, temperatura);
                framePai.revalidate();
                dispose();
            }
            else
            {
                controller.revertParedeChanges(indexParede);
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    Simulacao.getFrasePelaChave("uc1.janela.titulo"),
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    public void updateList()
    {
        modelMat.removeAllElements();
        modelEsp.removeAllElements();
        String[] mats = controller.getListaMateriaisParedes().get(indexParede);
        String[] esps = controller.getListaEspessurasParedes().get(indexParede);
        for (String focus:mats)
        {
            modelMat.addElement(focus);
        }
        for (String focus:esps)
        {
            modelEsp.addElement(focus);
        }
        listMateriais.setModel(modelMat);
        listEspessuras.setModel(modelEsp);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> listEspessuras;
    private javax.swing.JList<String> listMateriais;
    private javax.swing.JScrollPane spEspessuras;
    private javax.swing.JScrollPane spMateriais;
    private javax.swing.JTextField tempField;
    // End of variables declaration//GEN-END:variables
}
