/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.AlterarPropriedadesSalaController;
import java.awt.Frame;
import javax.swing.JOptionPane;
import model.Simulacao;

/**
 *
 */
public class AlterarPropriedadesSalaUI extends javax.swing.JDialog {

    private Frame framePai;
    private AlterarPropriedadesSalaController controller;
    private Simulacao simulacao;
    private SimulacaoWindow simWindow;
    
    /**
     * Creates new form AlterarPropriedadesSalaUI
     */
    public AlterarPropriedadesSalaUI(java.awt.Frame parent, boolean modal, Simulacao simulacao,SimulacaoWindow simW) {
        super(parent, Simulacao.getFrasePelaChave("uc1.janela.titulo"), modal);
        framePai = parent;
        this.simulacao = simulacao;
        simWindow=simW;
        controller = new AlterarPropriedadesSalaController(simulacao);
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtComprimento = new javax.swing.JTextField();
        lblComprimento = new javax.swing.JLabel();
        lblLargura = new javax.swing.JLabel();
        txtLargura = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        lblTeto = new javax.swing.JLabel();
        btnAlterarTeto = new javax.swing.JButton();
        lblParedes = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnParede1 = new javax.swing.JButton();
        btnParede3 = new javax.swing.JButton();
        btnParede2 = new javax.swing.JButton();
        btnParede4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtComprimento.setText(controller.getComprimento());

        lblComprimento.setText(Simulacao.getFrasePelaChave("uc1.janela.comprimento"));

        lblLargura.setText(Simulacao.getFrasePelaChave("uc1.janela.largura"));

        txtLargura.setText(controller.getLargura());

        lblAltura.setText(Simulacao.getFrasePelaChave("uc1.janela.altura"));

        txtAltura.setText(controller.getAltura());

        lblTeto.setText(Simulacao.getFrasePelaChave("uc1.janela.teto"));

        btnAlterarTeto.setText(Simulacao.getFrasePelaChave("uc1.janela.alterar"));
        btnAlterarTeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarTetoActionPerformed(evt);
            }
        });

        lblParedes.setText(Simulacao.getFrasePelaChave("uc1.janela.parede") + "s");

        btnGuardar.setText(Simulacao.getFrasePelaChave("uc1.janela.guardar"));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText(Simulacao.getFrasePelaChave("uc1.janela.cancelar"));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnParede1.setText(Simulacao.getFrasePelaChave("uc1.janela.parede") + " 1");
        btnParede1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParede1ActionPerformed(evt);
            }
        });

        btnParede3.setText(Simulacao.getFrasePelaChave("uc1.janela.parede") + " 2");
        btnParede3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParede3ActionPerformed(evt);
            }
        });

        btnParede2.setText(Simulacao.getFrasePelaChave("uc1.janela.parede") + " 3");
        btnParede2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParede2ActionPerformed(evt);
            }
        });

        btnParede4.setText(Simulacao.getFrasePelaChave("uc1.janela.parede") + " 4");
        btnParede4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParede4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblParedes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnParede1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnParede2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTeto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlterarTeto, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnParede3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnParede4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLargura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLargura))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAltura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAltura))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblComprimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtComprimento)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterarTeto, btnCancelar, btnGuardar, btnParede1, btnParede2, btnParede3, btnParede4});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblAltura, lblComprimento, lblLargura});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComprimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLargura)
                    .addComponent(txtLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParede2)
                    .addComponent(btnParede1)
                    .addComponent(lblParedes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParede4)
                    .addComponent(btnParede3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterarTeto)
                    .addComponent(lblTeto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarTetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarTetoActionPerformed
        new AlterarParedeUI(framePai, true, controller, simulacao, 4);
    }//GEN-LAST:event_btnAlterarTetoActionPerformed

    private void btnParede1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParede1ActionPerformed
        new AlterarParedeUI(framePai, true, controller, simulacao, 0);
    }//GEN-LAST:event_btnParede1ActionPerformed

    private void btnParede2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParede2ActionPerformed
        new AlterarParedeUI(framePai, true, controller, simulacao, 1);
    }//GEN-LAST:event_btnParede2ActionPerformed

    private void btnParede3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParede3ActionPerformed
        new AlterarParedeUI(framePai, true, controller, simulacao, 2);
    }//GEN-LAST:event_btnParede3ActionPerformed

    private void btnParede4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParede4ActionPerformed
        new AlterarParedeUI(framePai, true, controller, simulacao, 3);
    }//GEN-LAST:event_btnParede4ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            String opcoes[] = {Simulacao.getFrasePelaChave("menu.sim"), Simulacao.getFrasePelaChave("menu.nao")};
            int resposta = JOptionPane.showOptionDialog(
                    null, Simulacao.getFrasePelaChave("uc1.janela.mensagem"),
                    Simulacao.getFrasePelaChave("uc1.janela.titulo"), 0,
                    JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
            if (resposta == 0) {
                controller.guardarSala();
                simWindow.updateUniverse(simulacao.getSala());
                framePai.revalidate();
                dispose();
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    Simulacao.getFrasePelaChave("uc1.janela.titulo"),
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarTeto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnParede1;
    private javax.swing.JButton btnParede2;
    private javax.swing.JButton btnParede3;
    private javax.swing.JButton btnParede4;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblComprimento;
    private javax.swing.JLabel lblLargura;
    private javax.swing.JLabel lblParedes;
    private javax.swing.JLabel lblTeto;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtComprimento;
    private javax.swing.JTextField txtLargura;
    // End of variables declaration//GEN-END:variables
}
