package view;

import controllers.ImportarDadosController;
import java.awt.Frame;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Simulacao;

/**
 *
 */
public class ImportarDadosUI extends javax.swing.JDialog {

    private Frame framePai;
    private ImportarDadosController controller;

    /**
     * Creates new form ImportarDadosUI
     */
    public ImportarDadosUI(java.awt.Frame parent, boolean modal, Simulacao simulacao) {
        super(parent, Simulacao.getFrasePelaChave("uc8.janela.importar.titulo"), modal);
        this.controller = new ImportarDadosController(simulacao);
        this.controller.iniciarImportacao();
        this.framePai = parent;
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonImport = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jTextField = new javax.swing.JTextField();
        jButtonSpecify = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonImport.setText(Simulacao.getFrasePelaChave("uc8.janela.importar"));
        jButtonImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportActionPerformed(evt);
            }
        });

        jButtonCancel.setText(Simulacao.getFrasePelaChave("uc8.janela.cancelar"));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jTextField.setEnabled(false);

        jButtonSpecify.setText(Simulacao.getFrasePelaChave("uc8.janela.indicar"));
        jButtonSpecify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpecifyActionPerformed(evt);
            }
        });

        jLabel.setText(Simulacao.getFrasePelaChave("uc8.janela.importar.label"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonImport)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSpecify)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSpecify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImport)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportActionPerformed
        try {
            String caminhoTotal = this.jTextField.getText();
            int split = caminhoTotal.lastIndexOf("\\") + 1;
            
            String caminho = caminhoTotal.substring(0, split);
            String nome = caminhoTotal.substring(split);

            this.controller.setDados(caminho, nome);

            String opcoes[] = {Simulacao.getFrasePelaChave("menu.sim"), Simulacao.getFrasePelaChave("menu.nao")};
            int resposta = JOptionPane.showOptionDialog(
                    null, Simulacao.getFrasePelaChave("uc8.janela.importar.mensagem"),
                    Simulacao.getFrasePelaChave("uc8.janela.importar.titulo"), 0,
                    JOptionPane.QUESTION_MESSAGE, null, opcoes, opcoes[0]);
            if (resposta == 0) {
                ((JanelaPrincipal) framePai).setSimulacao(this.controller.importarDados());

                dispose();
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    ex.getMessage(),
                    Simulacao.getFrasePelaChave("uc8.janela.importar.titulo"),
                    JOptionPane.ERROR_MESSAGE);
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(
                    framePai,
                    Simulacao.getFrasePelaChave("uc8.janela.exportar.erro"),
                    Simulacao.getFrasePelaChave("uc8.janela.importar.titulo"),
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonImportActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSpecifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpecifyActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.showOpenDialog(this);
        
        if (jfc.getSelectedFile() != null) {
            this.jTextField.setText(jfc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jButtonSpecifyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonImport;
    private javax.swing.JButton jButtonSpecify;
    private javax.swing.JLabel jLabel;
    private javax.swing.JTextField jTextField;
    // End of variables declaration//GEN-END:variables
}
